service: s3select-hello-world

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::cleverorc/pathfinder/allCreatures.json"

functions:
  s3SelectQuery:
    memorySize: 128
    handler: src/shaefer/s3Select.query
    events:
      - http:
          path: shaefer/{id}
          method: get
          cors: true